### ISSUE TITLE
Alias working for where

### ISSUE THREAD

**Issue by daniel2d2art** [rails/arel#102]
Setting alias for table:

```
    a = Foo.arel_table
    a1 = a.alias("#{a.name}_1")
    a2 = a.alias("#{a.name}_2")

    inner_where = a1[:attr1].eq(a2[:attr1])
```

just working on joins:

```
a.join(a2).on(a1[:attr1].eq(a2[:attr1])).to_sql
```

returns:

```
"SELECT FROM \"foos\" 
  INNER JOIN \"foos\" \"foos_2\" 
          ON \"foos\".\"attr1\" = \"foos_2\".\"attr1\""
```

Same approach for nested where, no way:

```
a.where( a.where(inner_where).exists).to_sql
```

Don't express Alias for From clauses

```
    "SELECT FROM \"foos\"  
     WHERE EXISTS (SELECT FROM \"foos\"  
                   WHERE \"foos_1\".\"attr1\" = \"foos_2\".\"attr1\")"
```

Self subqueries needs some like:

```
        "SELECT FROM \"foos\" \"foos_1\" 
     WHERE EXISTS (SELECT FROM \"foos\" \"foos_2\"  
                   WHERE \"foos_1\".\"attr1\" = \"foos_2\".\"attr1\")"
```

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
