### ISSUE TITLE
Add bigdecimal to gemspec

### ISSUE THREAD

**Issue by bkabrda** [rails/arel#107]
Hi,
as I have also reported to the rails tracker [1], due to gemification of the Ruby standard library [2], I think you should include bigdecimal gem in gemspec of arel - if new version of bigdecimal is released, you will need to add it there anyway, so that bundler doesn't pick up the bigdecimal that is bundled in the standard Ruby installation.

Thank you!

[1] https://github.com/rails/rails/issues/5355
[2] https://bugs.ruby-lang.org/issues/5481

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
