### ISSUE TITLE
Generate non standard SQL?

### ISSUE THREAD

**Issue by rolftimmermans** [rails/arel#111]
I'm trying to generate two `UPDATE` queries that are functionally equivalent, but one is for MySQL and the other for PostgreSQL:

MySQL:

```
UPDATE a, (SELECT ...) b
SET a.foo = b.bar
WHERE a.id = b.id
```

PostgreSQL:

```
UPDATE a
SET a.foo = b.bar
FROM (SELECT ...) b
WHERE a.id = b.id
```

I'd like to generate these queries with Arel, because the conditions and updated columns are nontrivial. The MySQL version seems to be possible with some `SqlLiteral` hacking. I cannot figure out how to generate the PostgreSQL query, though, since there is no support for `FROM` in `UPDATE` statements.

If I wrote a patch to support `FROM` in `UPDATE` statements, would it be included in Arel? If not, is there a (supported) alternative way to use Arel to build non standard SQL queries like these? I'm trying to avoid having to do a lot of string manipulation. Thanks!

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
