### ISSUE TITLE
to_sql with safe binds

### ISSUE THREAD

**Issue by bfrog** [rails/arel#122]
Having to do something like

Arel.sql("my_stored_procedure(#{yadda}, #{nada})") is well, a bad thing to do but using Arel by itself
there's no way to use named binds which would be incredibly convenient .

If there is a way to use binds and I don't know about that it what would be great!

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
