### ISSUE TITLE
intersect outputs bad mysql syntax

### ISSUE THREAD

**Issue by aflag** [rails/arel#132]
Assume there's a one to many relationship between people and projects.

This arel query:

``` ruby
people.project(:id).join(services).on(services[:person_id].eq(people[:id])).where(services[:type].eq(1)).intersect(
    people.project(:id).join(services).on(services[:person_id].eq(people[:id])).where(services[:type].eq(2)))
```

outputs this SQL

``` sql
( SELECT id 
  FROM `people` INNER JOIN `services` ON `services`.`person_id` = `people`.`id` 
  WHERE `services`.`type` = 1
  INTERSECT 
  SELECT id 
  FROM `people` INNER JOIN `services` ON `services`.`person_id` = `people`.`id` 
  WHERE `services`.`type` = 2 )
```

problem is that it's not valid mysql (though you can work around it with inner join tricks). I can't seem to make such query play nicely with activerecord.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
