### ISSUE TITLE
UpdateManager doesn't have a way to add FOR UPDATE (pessimistic lock) in update subquery

### ISSUE THREAD

**Issue by dovgandy** [rails/arel#147]
Here's a sample UPDATE statement with FOR UPDATE subquery in PostgreSQL 9.2:

UPDATE tickets 
        SET purchased = TRUE
 WHERE ID in (
              SELECT id 
                 FROM tickets 
              WHERE NOT purchased
                   LIMIT 10 
                    FOR UPDATE
  )

I would expect to have this UPDATE statement from the following rails statement:
Ticket.where(:purchased => false).limit(10).lock(true).update_all(:purchased => true) 

but FOR UPDATE clause is not added because UpdateManager doesn't have a way to add FOR UPDATE (pessimistic lock) in update subquery. File: update_manager.rb. 

This is a screenshot from rails source where UpdateManager.lock should probably be called: http://bit.ly/RPsQ31

Is this something you think about adding in later versions or it was omitted with a purpose? I know such a FOR UPDATE lock was not supported in PostgreSQL before 9.0.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
