### ISSUE TITLE
SQL "AS" (`.as`) should be escaped

### ISSUE THREAD

**Issue by inossidabile** [rails/arel#155]
Currently it does not. I tried running `field.as("test.test")` and it fails at both: SQLite3 and PG. It injects passed string as-is without any escaping which is wrong.

**Comment by njvack** [comment]
I see this in MySQL -- for example:

```
Arel::Table.new('foo')[:bar].as('corge grault').to_sql
=> "`foo`.`bar` AS corge grault"
```

The result should be:

```
"`foo`.`bar` AS `corge grault`"
```

MySQL will also allow single quotes around the alias name, but I think backticks are more correct?

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
