### ISSUE TITLE
Add Arel::Nodes::FullOuterJoin and Arel::Nodes::RightOuterJoin

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [rails/arel#200]
If it's possible it would be interesting to add those contants, to allow us to make full outer join and right outer join in an arel fashion.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
