### ISSUE TITLE
Window function does not exist in MySQL

### ISSUE THREAD

**Issue by sword** [rails/arel#223]
As WINDOW function does not exist in MySQL (nearest is GROUP_CONCAT()), 3.0.3 breaks for MySQL.

visit_Arel_Nodes_SelectCore() in lib/arel/visitors/mysql.rb needs to set o.windows to empty array, as the method in lib/arel/visitors/to_sql.rb includes:

```
("WINDOW #{o.windows.map { |x| visit x }.join ', ' }" unless o.windows.empty?)
```

As o.windows is nil, an "(undefined method `empty?' for nil:NilClass)" error is raised

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
