### ISSUE TITLE
Make visitors functional - add a collector object

### ISSUE THREAD

**Issue by tenderlove** [rails/arel#251]
Rather than having the visitor class produce a concatenated SQL string, I want the collector object to do it.  I've introduced a new class called `Arel::Collectors::SQLString` that should be instantiated and passed to each `visit_*` method.

Each `visit_*` method should follow these rules:
1. Always return a collector object
2. Pass the returned collector from one `visit_` method to the next.  For example:

``` ruby
def visit_Something node, collector
  collector = visit_AnotherThing(node.left, collector)
  collector = visit_NextThing(node.right, collector)
  return collector
end
```

I've started the initial implementation in the `collector` branch.  Please look at the diff there and basically follow the pattern through the rest of the visitor objects.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
