### ISSUE TITLE
DELETE with a JOIN?

### ISSUE THREAD

**Issue by mdespuits** [rails/arel#296]
I am working on converting a few manual queries in the app I am working on into Arel. However, I cannot convert some of them because the `DeleteManager` does not support `JOIN` queries. Is there some way to do this that I am not aware of?

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
