### ISSUE TITLE
Arel::Visitors::MySQL doesn't parenthesize UNION ALL chains properly

### ISSUE THREAD

**Issue by firien** [rails/arel#299]
shouldn't #58 apply to `UNION ALL` as well?

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)

**Comment by kbrock** [comment]
Fix has been applied to Rails

**Comment by firien** [comment]
rails/rails@63dd8d8e12edb25d8d5bac324aacb1caf05bbe22
