### ISSUE TITLE
Add AliasPredication to Grouping

### ISSUE THREAD

**Issue by artempyanykh** [rails/arel#342]
Not sure if there is some good reason for not having `as` on a Grouping node, but from the SQL point of view this is a valid query:

``` sql
SELECT (column + 42) AS cool_column FROM some_table
```

However with Arel I can't do things like `(t[:column] + 42).as('cool_column')`.

Seems like it is enough to include 'Arel::AliasPredication`to`Arel::Nodes::Grouping` (and all tests pass).
Any thoughts?

**Comment by johncalvinyoung** [comment]
:+1: This a valid and important use case for us. I hate monkey-patching Arel to get things like this working.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
