### ISSUE TITLE
Can we use arel gem without rails

### ISSUE THREAD

**Issue by afzal-lakdawala** [rails/arel#350]
Hello,

I am ror developer, I know how to use arel gem with rails. But now requirement is diffrent. I want to use arel gem but without rails. I am using core ruby for development. Can anyone tell me how to connect with database and database pooling can be done?

**Comment by PriteshJain** [comment]
I don't think this works standalone then again I am not sure.

#### From Readme
>For the moment, Arel uses Active Record's connection adapters to connect to the various engines, > connection pooling, perform quoting, and do type conversion.

#### Standalone example with activerecord 
http://jpospisil.com/2014/06/16/the-definitive-guide-to-arel-the-sql-manager-for-ruby.html

**Comment by mcary** [comment]
The example in the Arel README seems to leave out a step of setting up Table.engine:

```Ruby
require 'arel'
table = Arel::Table.new(:users)
query = table.project(Arel.star)
query.to_sql
# => NoMethodError: undefined method `connection' for nil:NilClass
# from arel-6.0.3/lib/arel/tree_manager.rb:24:in `visitor'
# (nil came from Table.engine, which hasn't been set yet)
```

I'm interested in this case because I want to use Arel in settings where I can't wait for ActiveRecord to load (0.65 sec, +13MB rss, which might be mostly the activesupport dependency).

The engine is not so hard to implement; it just needs to respond to #connection:

```Ruby
engine = OpenStruct.new(connection: OpenStruct.new(visitor: visitor))
```

And the visitor is supplied by Arel.  But it needs a connection itself:

```Ruby
visitor = Arel::Visitors::MySQL.new connection
```

(The example in mysql2_adapter.rb also mixes in Arel::Visitors::BindVisitor; not sure if that's critical for this case.)

I haven't figured out how to create a suitable suitable implementation of connection without activerecord.  It looks like a more involved interface.  I needs to implement:

* quote(value, column), 
* quote_table_name(name), 
* quote_column_name(name)
* scheme_cache

The schema cache in turn needs to implement:

* data_source_exists?(name) (checks for existence of tables)
* columns_hash(table)

And the column object returned by columns_hash needs to implment:

* able_to_type_cast?
* type_cast_for_database(object)

I'd settle for loading just *part* of activerecord, but that's no small feat:

```Ruby
gem 'activerecord'
require 'active_record/connection_adapters/mysql_adapter'
# => NameError: uninitialized constant ActiveRecord::ConnectionAdapters::AbstractAdapter
require 'active_record/connection_adapters/abstract_adapter'
# => NoMethodError: undefined method `DelegateClass' for ActiveRecord::Type:Module
require 'delegate'
# Phew!  That worked.  Now try loading abstract_adapter again...
require 'active_record/connection_adapters/abstract_adapter'
# => NameError: uninitialized constant ActiveRecord::ConnectionAdapters::ActiveSupport
# ):  Need yet another gem.
# Ok, let's load it:
gem 'activesupport'
require 'active_support/dependencies/autoload'
require 'active_record/connection_adapters/abstract_adapter'
# => NoMethodError: undefined method `delegate' for ActiveRecord::ConnectionAdapters::DatabaseStatements:Module
# I guess we need another kind of delegation...
require 'active_support/core_ext/module/delegation'
require 'active_record/connection_adapters/abstract_adapter'
# => NameError: uninitialized constant ActiveSupport::Callbacks
# Ugh.
require 'active_support/callbacks'
require 'active_record/connection_adapters/abstract_adapter'
# FTW!
require 'active_record/connection_adapters/mysql_adapter'
```

Ok, it's loaded.  Now, how to create a connection?

```Ruby
# This underlying connection doesn't seem to actually be used...
mysql = Mysql.init
Mysql.real_connect("localhost", "root", nil, ...)
connection = ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter.new(mysql, Logger.new(STDOUT), [], {})
```

Then create `visitor` and `engine` from that, and assign to `Arel::Table.engine`.  And and recreate the table.  And...

```Ruby
query.to_sql
# => "SELECT * FROM `users`"
# w00t!
```

The final list of steps:

```Ruby
require 'arel'

gem 'activesupport'
require 'active_support/dependencies/autoload'
require 'active_support/core_ext/module/delegation'
require 'active_support/callbacks'

gem 'activerecord'
require 'active_record/connection_adapters/abstract_adapter'
require 'active_record/connection_adapters/mysql_adapter'

mysql = Mysql.init
Mysql.real_connect("localhost", "root", nil)
require 'logger'
connection = ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter.new(mysql, Logger.new(STDOUT), [], {})

visitor = Arel::Visitors::MySQL.new connection
require 'ostruct'
engine = OpenStruct.new(connection: OpenStruct.new(visitor: visitor))

Arel::Table.engine = engine

table = Arel::Table.new(:users)
query = table.project(Arel.star)
query.to_sql
```

Awesome, it works!  It generates the SQL.

The only problem is that now this takes 1.2 sec and grows my Ruby process's RSS by 22 MB.  Even if I skip the network connection to MySQL (which doesn't seem to be used) it doesn't safe a noticeable amount of time or memory.
