### ISSUE TITLE
Mix `Arel::Math` into `Arel::Nodes::Grouping`

### ISSUE THREAD

**Issue by carsomyr** [rails/arel#364]
Notice that `Arel::Math` returns `Arel::Nodes::Grouping` nodes to enforce operator precedence of `*` and `/` over `+` and `-`. If `Arel::Math` isn't mixed in, then you won't be able to do stuff like

```
(a[:col] + b[:col]) / (c[:col] + d[:col])
```

and will instead get a `NoMethodError`.

**Comment by kbrock** [comment]
Suggestion:  Why not just create a PR with this same statement?

That way if someone agrees this needs to be fixed, they can just click merge.

Seems you already gave the test case and solution.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
