### ISSUE TITLE
Division between relations.

### ISSUE THREAD

**Issue by jcarpanelli** [rails/arel#371]
Hi! I've been reading the documentation of this gem and I didn't find anything about division between relations (https://en.wikipedia.org/wiki/Relational_algebra#Division_.28.C3.B7.29). I find really useful this AR operator for doing some specifical queries I usually have to work with. Is there any implementation of this operator in this gem?
Thanks!

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
