### ISSUE TITLE
needs a way to use `between` predicate with other columns

### ISSUE THREAD

**Issue by lx00st** [rails/arel#394]
I need a way to use `between` predicate with other columns. Now it seems that it work with ranges only, but I need smth like 
`
  table[:column].between(table[:since]..table[:till])
`

**Comment by ah-tunecore** [comment]
:+1:  I ran into this same need yesterday.

**Comment by kbrock** [comment]
So this can be accomplished in 2 ways.

1. introduce 2 parameter variant of between: `table[:column].between(table[:since], table[:till])`
2. Introduce `<=>` method to `Arel::Attributes::Attribute`.

Which one sounds like the best plan?

**Comment by matthewd** [comment]
> introduce 2 parameter variant of between

:+1:

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
