### ISSUE TITLE
unnecessary parens when combining multiple "UNION ALL" (mysql)

### ISSUE THREAD

**Issue by bughit** [rails/arel#404]
https://github.com/brianhempel/active_record_union/pull/4#issuecomment-163079230

to repro:

use `gem 'active_record_union', github: 'odedniv/active_record_union'` in a rails (with mysql) project then with any model run the following:

``` ruby
User.where(id: 1).union(User.where(id: 2), User.where(id: 3)).to_sql
```

``` sql
SELECT `users`.* FROM ( (SELECT `users`.* FROM `users` WHERE `users`.`id` = 1) UNION (SELECT `users`.* FROM `users` WHERE `users`.`id` = 2) UNION (SELECT `users`.* FROM `users` WHERE `users`.`id` = 3) ) `users`
```

``` ruby
User.where(id: 1).union_all(User.where(id: 2), User.where(id: 3)).to_sql
```

``` sql
SELECT `users`.* FROM ( ( (SELECT `users`.* FROM `users` WHERE `users`.`id` = 1) UNION ALL (SELECT `users`.* FROM `users` WHERE `users`.`id` = 2) ) UNION ALL (SELECT `users`.* FROM `users` WHERE `users`.`id` = 3) ) `users`
```

note the extra grouping with `UNION ALL`

**Comment by kbrock** [comment]
Please let me know if #510 meets your needs (and if it works)

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)

**Comment by kbrock** [comment]
Merged into Rails
