### ISSUE TITLE
for sqlite, multiple union sub-queries are emitted grouped (parens) which sqlite can not handle

### ISSUE THREAD

**Issue by bughit** [rails/arel#418]
https://github.com/brianhempel/active_record_union/pull/4#issuecomment-198833562

using `gem 'active_record_union', github: 'odedniv/active_record_union'` with sqlite

``` ruby
Post.where(id: 1).union(Post.where(id: 2), Post.where(id: 3), Post.where(id: 4)).to_sql
```

produces

``` sql
SELECT "posts".* FROM (
  (
    (
      SELECT "posts".* FROM "posts" WHERE "posts"."user_id" = 1
      UNION
      SELECT "posts".* FROM "posts" WHERE "posts"."id" = 2
    )
    UNION
    SELECT "posts".* FROM "posts" WHERE "posts"."id" = 3
  )
  UNION
  SELECT "posts".* FROM "posts" WHERE "posts"."id" = 4
) "posts"
```

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)

**Comment by kbrock** [comment]
Fix has been merged into Rails
