### ISSUE TITLE
InsertManager not wrapping escaped values in correct double-quotes

### ISSUE THREAD

**Issue by henrytseng** [rails/arel#479]
It looks like InsertManager isn't wrapping characters that are escaped with double-quotes correctly for MySQL to read.  

It's rendering the following:
`INSERT INTO `test` (`name`) VALUES ('Bob\'s Org Group');`

From: 
`insert_manager = Arel::InsertManager.new().into(posts); insert_manager.insert([[posts[:name], "Bob\'s Org Group"]]); insert_manager.to_sql`

**Comment by henrytseng** [comment]
Looks like this is method is delegated to `connection.quote()` but the `ActiveRecord::ConnectionAdapters::Mysql2Adapter` is not quoting correctly for MySQL

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
