### ISSUE TITLE
SqlLiteral does not serialize/de-serailize correctly

### ISSUE THREAD

**Issue by bobf** [rails/arel#509]
``` ruby
require 'psych'
require 'arel'
yaml = Arel::Nodes::SqlLiteral.new('*').to_yaml
puts Psych.load(yaml).is_a?(Arel::Nodes::SqlLiteral) # false
```

I have submitted a PR (https://github.com/rails/arel/pull/503) to fix but haven't had any feedback (posted 20 days ago) so hoping to gain a bit of traction by raising a bug as well.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
