### ISSUE TITLE
Timestamp between columns, how can i do it?

### ISSUE THREAD

**Issue by groony** [rails/arel#534]
working example without arel
```ruby
User.where(':datetime BETWEEN users.started_at AND users.ended_at', datetime: Time.zone.now)
```

What i want to
```ruby
table = User.arel_table
User.where(1.day.ago.between(table[:started_at]..table[:ended_at])) 
```

How can i do it?

**Comment by sgrif** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
